# Generated by Django 2.2.1 on 2019-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190518_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('qury_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=80)),
                ('desc', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
